import type { Metadata } from "next";
import "@/styles/globals.css";
import Header from "@/components/layout/Header";
import Main from "@/components/layout/Main";

export const metadata: Metadata = {
    title: "MAC HUB",
    description: "Generated by create next app and developed by @arthur.vsl",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            className="
                art:w:device
                art:h:device
                art:bg:white-01
                art:font:black-01
            "
            lang="pt-br"
        >
            <body
                className="
                    art:h:device
                    art:flex 
                    art:gap:lg
                    art:col 
                    art:m:base 
                    art:flex 
                    art:align-items:center 
                    art:flex:col
                ">
                <Header />
                <Main>{children}</Main>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime repudiandae repellat voluptates culpa dolorem qui vel nostrum consectetur totam ullam? Eius repudiandae quaerat quidem architecto possimus magni, ratione officia? Ipsum.</p>
            </body>
        </html>
    );
}
